name: Update Project
run-name: ${{ gitea.actor }} is updating project ðŸš€
on: [ push ]

jobs:
    update:
        runs-on: [ ubuntu-latest ]
        steps:
            - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ gitea.event_name }} event."
            - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by Gitea!"
            - name: Configure SSH
              run: |
                  mkdir -p ~/.ssh/
                  echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/staging.key
                  chmod 600 ~/.ssh/staging.key
                  cat >>~/.ssh/config <<END
                  Host staging
                    HostName $SSH_HOST
                    User $SSH_USER
                    IdentityFile ~/.ssh/staging.key
                    StrictHostKeyChecking no
                  END
                  cat ~/.ssh/config
              env:
                  SSH_USER: ${{ secrets.PRIVATE_USER }}
                  SSH_KEY: ${{ secrets.PRIVATE_KEY }}
                  SSH_HOST: ${{ secrets.PRIVATE_VDS }}

            - name: Update Project
              run: ssh staging 'cd ${{ secrets.PROJECT_ROOT }} && git pull'

            - name: Restart Container
              run: |
                  ssh staging 'bash ${{ secrets.PROJECT_ROOT }}/docker/deploy.sh'
