version: "3.7"

services:
    adminer:
        container_name: ${APP_NAME}-adminer
        image: adminer
        environment:
            - ADMINER_DESIGN=nette
        ports:
            - 9990:8080
